import { PROJECT_STATUSES, PROJECT_TYPES } from "./constants";
import { ProjectConfig } from "./types";

export const MOTHERHUNT_KEY = "motherhunt";

export const MOTHERHUNT_CONFIG: ProjectConfig = {
  key: MOTHERHUNT_KEY,
  title: "MotherHunt",
  externalLinkUrl: "https://www.motherhunt.com",
  backgroundFileName: "motherhunt_bg.png",
  status: PROJECT_STATUSES.TESTNET,
  type: PROJECT_TYPES.WEB3_SAAS,
  techStack: [
    "Next.js",
    "Turborepo",
    "PayloadCMS",
    "BetterAuth",
    "RBAC",
    "Solidity",
    "Nodemailer",
    "Framer Motion",
    "TanStack Query"
  ],
  colors: {
    background: "#3e359c",
    card: "hsla(302,46%,57%,0.819)",
    mutedForeground: "#359c78",
    accentForeground: "#b52971",
  },
  diagramsFileNames: [
    "product_ecosystem",
    "runtime_boundaries",
    "monorepo_workspace",
    "deployment",
    "environment",
    "backend",
    "api_contract",
    "auth",
    "rbac",
    "locales",
    "router",
    "data_flow",
    "write_flow",
    "indexer",
    "caching",
    "deployment_gate",
    "cms_gate",
    "contracts_deployment",
    "failure_scenarios",
    "smart_contracts",
    "onchain_events",
    "indexer_processing",
    "cron_reconciler",
    "web3_writing",
    "business_domains",
    "data_split",
    "auction",
    "bids",
    "voting",
    "auction_workspace",
    "lot_privacy",
    "agency_application",
    "org_switch",
    "chats",
    "governance",
    "content",
    "cms_cache",
    "live_market",
  ],
};
